version: 2.1
orbs:
  architect: giantswarm/architect@5.11.6

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-catalog
          context: architect
          executor: app-build-suite
          chart: kube-state-metrics
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          ct_config: .circleci/ct.yml
            # Trigger job on git tag.
          filters:
            branches:
              ignore:
              - main
              - master
            tags:
              only: /^v.*/