version: 2.1

orbs:
  architect: giantswarm/architect@5.13.1

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          name: push-to-default-catalog
          context: architect
          executor: app-build-suite
          chart: kube-state-metrics
          ct_config: .abs/ct.yaml
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/
