version: 2.1
orbs:
  architect: giantswarm/architect@5.11.6

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: giantswarm-app-catalog
          app_catalog: giantswarm-catalog
          app_catalog_test: giantswarm-test-catalog
          chart: 'kube-state-metrics'
          ct_config: ".circleci/ct-config.yml"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main
              - master
      
      - architect/push-to-app-catalog:
          name: app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          chart: 'kube-state-metrics'
          ct_config: ".circleci/ct-config.yml"
            # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main
              - master
      
      - architect/push-to-app-catalog:
          name: control-plane-app-catalog
          context: architect
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: 'kube-state-metrics'
          ct_config: ".circleci/ct-config.yml"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main
              - master
      